trigger:
- master

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: 'Use Python 3.6'

- task: MicrosoftSecurityDevOps@1
  inputs:
    tools: 'bandit'